Added "Features" submenu section
ReinisZogots/training-website pull request #10
Opened 2021-11-23 10:52 UTC by ReinisZogots

![sub_navigation_open](https://user-images.githubusercontent.com/68864184/143011307-94af1061-c557-4347-97ac-6262a42f864a.png)

https://reiniszogots.github.io/training-website/

2021-11-23 12:13 UTC, ilze-dom commented on js/main.js
> +    for (i = 0; i < mainmenusection.length; i++) {
I would use arry map method for these kinds of things
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

But why are you adding a css clases here?

2021-11-23 12:14 UTC, ilze-dom commented on js/main.js
> +    var i;
variable type let is better than var

2021-11-23 12:17 UTC, ilze-dom approved these changes

2021-11-23 13:39 UTC, ReinisZogots commented on js/main.js
> +    var i;
It is because of scope, right? Changed to let.

2021-11-23 13:48 UTC, ReinisZogots commented on js/main.js
> +    for (i = 0; i < mainmenusection.length; i++) {
I figured that I would hide the main menu and show the submenu by adding/removing classes. Is it a bad idea?

2021-11-24 08:12 UTC, Jose-Hash-Dev requested changes

2021-11-24 08:12 UTC, Jose-Hash-Dev commented on js/main.js
> +var mainmenusection = document.querySelectorAll(".navigation-menu__menu-section");
Do you change the value of `mainmenusection`? If not then you should use `const`. Also try to use `let` instead of `var`.

[https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/](url)

2021-11-24 09:29 UTC, VSlobolinskyi commented on css/style.css
> +.navigation-submenu__back-text {
Why do you have back as a link? I think you should make it into a regular p or a button as it isn't supposed to lead to a page

2021-11-24 09:29 UTC, VSlobolinskyi commented on js/main.js
> +var mainmenusection = document.querySelectorAll(".navigation-menu__menu-section");
I also want to add that if you were to make it into constant you still will be able to change the object this variable references

2021-11-24 09:29 UTC, VSlobolinskyi commented on js/main.js
> +const opensubmenu = document.querySelector('#open-submenu');
I would suggest to use getElementById instead of querySelector

2021-11-24 09:29 UTC, VSlobolinskyi commented on js/main.js
> +    for (i = 0; i < mainmenusection.length; i++) {
The question would be why do you add it to each separate <li> instead of whole menu

2021-11-24 10:40 UTC, ReinisZogots commented on css/style.css
> +.navigation-submenu__back-text {
Removed text-decoration: none;

2021-11-24 10:43 UTC, ReinisZogots commented on js/main.js
> +const opensubmenu = document.querySelector('#open-submenu');
corrected

2021-11-24 13:13 UTC, VSlobolinskyi approved these changes

2021-11-24 13:16 UTC, Jose-Hash-Dev approved these changes

2021-11-24 13:40 UTC, merged

2021-11-26 10:12 UTC, VSlobolinskyi reviewed
Review