Feature/fixed menu
ReinisZogots/training-website pull request #12
Opened 2021-12-01 14:45 UTC by ReinisZogots

https://reiniszogots.github.io/training-website/

1. Carousel button click area resized
2. About section picture position does not change when resizing
3. Shopping cart menu must close when main menu is opened and the other way around
4. Footer social media links open in a new tab
5. Search field width takes up the whole free space of the menu section
6. Menu sections clickable area takes up the whole section
7. Changed carousel slide width from 33.3333% to calc(100% / 3)
8. Changed z-index to bigger numbers(instead 1 use 10; 3 =30 and so on) therefore leaving space for future additional elements that could be inserted between them.
9. Renamed clearClass to removeAddedSliderClasses in JS

2021-12-01 15:11 UTC, VSlobolinskyi approved these changes

2021-12-01 15:23 UTC, YuraLeo94 requested changes
Should this `about` looks like this? (Mobile L)
<img width="236" alt="about view" src="https://user-images.githubusercontent.com/71021726/144262029-ec4cc063-bc02-42ae-a08d-74dcc5f86101.PNG">
@VSlobolinskyi  what do you think about it?

2021-12-01 15:23 UTC, YuraLeo94 commented on js/main.js
> +cartchbox.addEventListener("change",() => {
space` ("change", () => `

2021-12-02 08:46 UTC, YuraLeo94 reviewed
If it's a feature not issue just ignore this comment.
If it is an issue I think you can use percentage to solve it
![image](https://user-images.githubusercontent.com/71021726/144388167-b29a8eeb-381d-429a-ab16-842881587416.png)

2021-12-02 08:47 UTC, YuraLeo94 approved these changes

2021-12-02 08:51 UTC, merged