Feature/carousel functionality version2
ReinisZogots/training-website pull request #8
Opened 2021-11-08 20:51 UTC by ReinisZogots

2021-11-09 07:57 UTC, VSlobolinskyi requested changes

2021-11-09 07:57 UTC, VSlobolinskyi commented on js/main.js
> +        carousel.style.justifyContent = 'flex-start';
Don't use inline styles. If you need to add or remove some property toggle class. If it's not possible then you will have to re-think your logic.

2021-11-09 07:57 UTC, VSlobolinskyi commented on js/main.js
> +        slider.style.transform = 'translate(-33.3333%)';
Class

2021-11-09 07:57 UTC, VSlobolinskyi commented on js/main.js
> +    slider.style.transform = 'translate(33.3333%)';
class

2021-11-09 07:57 UTC, VSlobolinskyi commented on js/main.js
> +        slider.style.transition = 'all 0.5s';
class

2021-11-10 17:10 UTC, VSlobolinskyi commented on css/style.css
>      width: 300%;
Why do you have with: 300%?

2021-11-10 17:16 UTC, ReinisZogots commented on css/style.css
>      width: 300%;
because there are 3  slides

2021-11-10 18:42 UTC, VSlobolinskyi approved these changes

2021-11-10 21:35 UTC, merged