Added navigation dropdown menu with icon animation
ReinisZogots/training-website pull request #9
Opened 2021-11-16 15:22 UTC by ReinisZogots

1. Navigation icon changes from hamburger to close icon, using CSS.
2. Navigation has to look smooth with animations using CSS.
3. Navigation items must become active once clicked on.
4. Added search field with placeholder and search icon.
5. Added sublevel button layout for "Features" navigation section.

Should look like this:
![navigation_open](https://user-images.githubusercontent.com/68864184/142013338-23a85479-c6e3-4710-94fa-1206dc5fbfc2.png)

2021-11-17 09:49 UTC, VSlobolinskyi requested changes

2021-11-17 09:49 UTC, VSlobolinskyi commented on css/style.css
> +    position: relative;
It's relative by default

2021-11-17 09:49 UTC, VSlobolinskyi commented on css/style.css
> +    margin: 20px 20px 20px 10px;
Could be shortened

2021-11-17 09:49 UTC, VSlobolinskyi commented on index.html
> +                        <a href="#" class="navigation-menu__menu-text">features</a>
It would make more sense to have a regular p tag here, cause it will open submenu and won't redirect you anywhere.

2021-11-17 14:12 UTC, ReinisZogots commented on css/style.css
> +    position: relative;
Isn't it static by default? I only added position relative to this div because it's child element has position absolute . Since it is the top element it makes no difference. Will remove it.

2021-11-17 16:43 UTC, Jose-Hash-Dev requested changes

2021-11-17 16:43 UTC, Jose-Hash-Dev commented on css/style.css
> +    margin: 20px;
`margin: 20px;` is overwritten, you have already set it 20px in line _143_

2021-11-19 11:07 UTC, ReinisZogots commented on css/style.css
> +    margin: 20px;
Removed margin: 20px
Used "flex: none" instead of "flex-shrink: 0" for carousel__item-container . Removed "flex-basis", "flex-shrink" and "flex" from carousel__item, turns out they were redundant.

2021-11-19 11:11 UTC, ReinisZogots commented on index.html
> +                        <a href="#" class="navigation-menu__menu-text">features</a>
changed to p

2021-11-19 11:19 UTC, Jose-Hash-Dev approved these changes

2021-11-21 15:07 UTC, VSlobolinskyi approved these changes

2021-11-22 10:10 UTC, merged